baseURL = "https://example.com"
languageCode = "en-us"
title = "Dimension for Hugo"
theme = "dimension"
# googleAnalytics = "UA-123-45"

[params]
    author = "Dmitry Pechnikov"
    description = "The Dimension template from HTML5 UP adapted for Hugo static site generator."
    copyright = "<a href=\"https://dmitrypechnikov.xyz\">Dmitry Pechnikov</a>"

    # disableLogo = false
    # logo = "diamond"
    # titleFontSize = "2.25rem"
    # subtitleFontSize = "0.8rem"
    # baseFontSize = "1.0rem"
    # overlayOpacityPercentage = "50"
    # disableImageOverlay = false
    # modalWidth = "40rem"

    # customCSS = "custom.css"
